README.md

Change alt text

---

README.md

Just thought that, numbering would help to keep tracking

Updated Bullets to numbers in toc and section heading

---

README.md

They usually have easily understandable and well thought out documentation.

add MDN link for #2

---

README.md

Added [Checking for the Absence of a Value in JavaScript](https://tomeraberba.ch/html/post/checking-for-the-absence-of-a-value-in-javascript.html) article to the "== vs === vs typeof" section. Addresses #17.

Checking for the Absence of a Value in JavaScript

---

README.md

Added Learning JavaScript Design Patterns - Addy Osmani

Added Learning JavaScript Design Patterns

---

README.md

Added Functional-Light JavaScript 3: Managing Function Inputs by Kyle Simpson

Added Functional Light JS Chapter 3

---

README.md

Hi Leonardo,
Awesome links in this project, but I noticed there are no videos in the async/await section.
So I remembered a talk by Wes Bos that I watched some while ago and I think might be useful.

Add async/await video

---

README.md

Update to 'Back to Top'

---

README.md

The async await section looks pretty light, I really enjoyed Shelley's talk at JSconf EU 2018 which covers async await very well and alot more.

Add Asynchrony: Under the Hood - Shelley Vohr

---

README.md

An amazingly informative video for javascript prototype; covers a variety of patterns for instantiating new objects and in doing so, you'll be gradually led to understanding JavaScript's prototype in depth.

A Beginner's Guide to JavaScript's Prototype

---

README.md

Everything you never wanted to know about JavaScript numbers by Bartek Szopka, very good and visual explanation on IEEE 754

Add video on floating point numbers

---

README.md

Very good tutorial "Async / await in JavaScript - What, Why and How" by Fun Fun Function youtube channel (Mattias Petter Johansson)

add async/await video resource

---

README.md

Hi, Leonardomso !
Thanks for these guides, now I want to add my blog link to community list,
maybe can help other Chinese developer to get started this great guide

add a link to Chinese guides

---

README.md

Add @jakearchibald's 2018 talk named [**In The Loop**](https://www.youtube.com/watch?v=cCOL7MC4Pl0) to section *9. Message Queue and Event Loop*.

Add In The Loop talk to section 9.

---

README.md

Added [You Don't Know JS: this & Object Prototypes](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/ch4.md)

Added to Prototype Inheritance and Prototype Chain

---

README.md

Added information about generators #45

---

README.md

JavaScript Patterns for 2017 by Scott Allen: https://youtu.be/hO7mzO83N1Q

Additional video resource on Design Patterns

---

README.md

Add functional programming video

---

README.md

Thought it would be more readable.

Translation list markup update

---

README.md

thought the section was lacking in video's and added one i thought was useful

added useful video

---

README.md

I put the link of repository which has Korean version of README.md at the original README.md

I just translated README.md into Korean

---

README.md

Add link to my Repo Translate in Spanish

[Add] Translation to spanish

---

README.md

- Added Link to Russian Translations

docs: add link to russian translations

---

README.md

Great article with examples of how we can use Design Patterns in your daily jobs to improve code quality.

Add article about Design Pattern from Medium.

---

README.md

Add Vietnamese translate

---

README.md

Reverts leonardomso/33-js-concepts#79

Revert "Added link to Polish translation"

---

README.md

Added [**Tasks, microtasks, queues and schedules**](https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/) by Jake Archibald

Updated: Message Queue and Event Loop

---

README.md

Update French translation author

---

README.md

Add links to lessons in channel fun fun function

Add MPJ Lessons

---

README.md

I'd like to add Philip Roberts' video about the browser event loop.  I have a working example of his event loop application hosted on heroku: https://event-loop-tool.herokuapp.com

Add event loop / call stack video resource

---

README.md

Add Greek translation

---

README.md

His videos are truly amazing, It would be awesome If his video makes it to the list.
Also, this project has helped me a lot to get ready for job interview and I would be great if this repository is my first ever contribution to an open source project.
Thank you!

26. async/await added Colt Steele new video

---

README.md

Add Japanese Translation

---

README.md

In working my way through your awesome repo trying to learn all the key concepts, I came across this video. It was amazing and really helped me understand the concept of typing, not only in Javascript but in programming in general.
I really hope you see fit to include it, but thanks again for your great resource. 🙏🏽

adds new resource to help understand typing in Javascript

---

README.md

Hi my name is Sacha and I recently uploaded a video about the Call Stack to my [YouTube channel](https://lacocinadelcodigo.com).
It would be great if you could add the link to it. It's in Spanish as I'm from Argentina, I hope that's not a problem.
Also, thank you very much for this repo it's been very helpful to understand some difficult concepts of the language.
Best,
Sacha

[Call Stack] Add 1 new video

---

README.md

Add a new link for a new video on my YouTube channel.

Add Primitive Data Types new video

---

README.md

Understanding `super` in JavaScript

Adding article to 'Factories and Classes' section

---

README.md

I added two new videos to my YouTube channel on the playlist based on this repository: one for Value Types and Reference Types and the other one related to the 4th concept: JavaScript Type System, analyzing static vs dynamic type checking, type safety, implicit and explicit conversions and nominal, structural and duck typing.

Add 2 new videos

---

README.md

I've translated most of the Readme file to Arabic, some things don't have an Arabic translation, especially the technical terms. However, I'm open to updating the translation and accepting PRs to improve it.

Add Arabic translation

---

README.md

Added an article to Promises section

Added an article to Promises section

---

README.md

Both 2 and 6 video resource are same . So I remove 6th video link Is That ok.
Note Link: (JavaScript Practical Applications of Call, Apply and Bind functions — techsith)

Same Video

---

README.md

Added an article to list no. 15 (this, call, apply, bind)

Added an article to list no. 15 (this, call, apply, bind)

---

README.md

Update the blog's broken URL under Chapter 2 named  **(Not) Everything in JavaScript is an Object — Daniel Li** with an active one.

Blog URL Update

---

README.md

Added the article to help to understand 'this' binding. https://yasemincidem.medium.com/understanding-this-binding-in-javascript-86687397c76d

Added 'this' binding article

---

README.md

Recently I came across Akshay Saini's, "Namaste Javascript" playlist, I found that series explanation are so great, thought of adding one here.

Best Call Stack explanation

---

README.md

Removed video link that is no longer available, you can check just trying to go to this link
[https://www.youtube.com/watch?v=PylQlISSH8U&list=PLujX4CIdBGCa-65N3uN8CDbUMrYsHBrz-](https://www.youtube.com/watch?v=PylQlISSH8U&list=PLujX4CIdBGCa-65N3uN8CDbUMrYsHBrz-)

Data Scructures | Removed video link that is no longer available

---

README.md

Added articles and video URL for the topic called **Event Propagation** as it's an important topic that was missing and will be helpful for every JS Developer.

Added articles and video lecture link for Event Propagation

---

README.md

- The original article got shifted from hackernoon to medium
- This closes [Issue-163](https://github.com/leonardomso/33-js-concepts/issues/163)

updated broken url

---

README.md

Add Video of Higher-Order Functions by Akshay Saini

Add Video of Higher-Order Functions

---

README.md

hacktoberfast

---

README.md

Hey, I have added a helpful reference link for javascript functions that I think will best add to your content and give your readers a more diverse understanding of the topic. I hope you will like this. Thank you.

Added one useful resource for javascript functions

---

README.md

Included an Event Loop video reference in Portuguese (Brazil).

Update README.md - Added a PT-BR video reference about the Event Loop

---

README.md

add Thai document version link.

add Thai translation into README.md

---

README.md

thanks for the privilege of contributing to the Read.md

modelist123 js videos

---

README.md

I included two new resource for async and await (one article and one video)

Included new resources for async await

---

README.md

I included new resource for javascript promises which would be very helpful.

included an article and a video resource for promises in the english version

---

README.md

Non-working video of Expression vs statement updated. A new video with a proper explanation was added.

Video of Expression vs Statement section changed

---

README.md

Added [this article](https://blog.usman-s.me/array-map-in-javascript-a-simple-method-made-simpler) in the Array Map category

Added an article for array map method

---

README.md

I have added new resources for type comparison (== vs ===) and fixed old link errors in line 164

Added new resources and fixed old link errors

---

README.md

How Javascript code is executed and how it works behind the scenes video reference added in JS engine section.

Update in Javascript engine section

---

README.md

Adding a link to a very easy-to-understand video on Javascript promises which can be helpful a lot for beginners.

feat: added video link for Js Promise

---

README.md

- Added youtube video link to learn Closures

Added new video resource to learn Closures

---

README.md

added new blog resource for setTimeout, javascript engines and Primitive Types

added new blog resource

---

README.md

- 📜 [Var, Let, and Const – What's the Difference?](https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/) Added this link instead of - 
📜 [The battle between Function Scope and Block Scope — Marius Herring](http://www.deadcoderising.com/2017-04-11-es6-var-let-and-const-the-battle-between-function-scope-and-block-scope/) as this link does not exist anymore
Issue: https://github.com/leonardomso/33-js-concepts/issues/336

Fixed a Broken Link

---

README.md

Added Video Link in Point 15 - `this, call, apply and bind` in README.md

Update: Added Video Link in Point 15 in README.md

---

README.md

https://github.com/smnv-shokh/33-js-concepts

Add Uzbek translation

---

README.md

Add Urdu translation

---

README.md

previously, my branch conflicted with the main one, to sync fork I had to delete my previous commit
here is the updated pull request
translated repo: https://github.com/Jisan-mia/33-js-concepts

Add Bangla translation

---

README.md

This is a really useful concept to know and something I've used many times in projects. 
Debouncing is a way to delay a function, this is useful for cases where you don't want a function to run every single time a user does something, as a way to reduce browser and even server load. For example, a user might be using a search bar - instead of running the function every time a user presses a key, we might only want the function to run after a few hundred milliseconds AFTER we stop typing.

Add link to debouncing article

---

README.md

Fixes #380 
gujarati translation of README.me added.
view the translated file here: [GUJARATI README](https://github.com/VatsalBhuva11/33-js-concepts)

add gujarati translation

---

README.md

Updated README.md to add the Bhojpuri Translated link in README.md
the bhojpuri README link:- [BHOJPURI README](https://github.com/debnath003/33-js-concepts)
#394
@leonardomso 
also if possible please include hacktoberfest-accepted label so that it can be eligible for hacktoberfest

Bhojpuri Translation

---

README.md

/resolve: #396 Add sindhi translation link in README.md

/resolve: #396 Update README.md

---

README.md

Translated all that could be translated, preserved the natural tone and meaning of the author. Thank you for this compendium of JavaScript knowledge!

Add Bulgarian translation

---

README.md

The article from digital ocean 'Dealing With Objects in JavaScript With Object.assign, Object.keys, and hasOwnProperty' returned a 404 status error. So the external link was being updated with a new link to the same page.

404 Status Error

---

README.md

I added the call stacks video link from CS50. The youtube link is-
https://www.youtube.com/watch?v=aCPkszeKRa4
Thank you.

Added Call Stack Useful link 

---

README.md

The previous article from 'thecodingdelight.com' about the topic of 'recursion' wasn't accessible. So a new article that explains recursions in a solid way was added by replacing the previous one. I have also checked whether any articles about javascript recursions were on the site 'thecodingdelight.com' but there were none. You can also use this Google search trick to find out (site:sitename.com "your keyword to search")

Previous Article Returned 404

---

README.md

An awesome article from **javascripttutorial.net** which dives deep into IIFE. Talks about _Why IIFEs, Named IIFE, IIFE starting with a semicolon (;), IIFE in actions, jQuery & IIFE_ with beginner-friendly examples that make sense for first-time IIFE learners.

JavaScript Immediately Invoked Function Expression

---

README.md

Source: https://www.youtube.com/watch?v=6oDQaB2one8 
Author: Web Dev Simplified

Added a Video Resource for Recursion

---

README.md

**Description:**
This pull request updates the video link for 'TRUST ISSUES with setTimeout() — Akshay Saini' in the 'setTimeout, setInterval and requestAnimationFrame' section of the README. The new link provides a better explanation of the topic.
**Link:**
- 🎥 [TRUST ISSUES with setTimeout() — Akshay Saini ](https://youtu.be/nqsPmuicJJc?si=4FXKlZfqiJUqO2Y4)
**Additional Context:**
The updated video delves into common trust issues associated with `setTimeout()` in JavaScript, which is crucial for understanding the topic.
**Testing:**
I've tested the link, and it's working as expected.
**Reviewer Request:**
@leonardomso 
**Description (Extended):**
The updated 'TRUST ISSUES with setTimeout() — Akshay Saini,' is a video that explores the principles of `setTimeout()` and how it operates …

Update : Added Working principle and TRUST ISSUES with setTimeout() Video Link

---

README.md

Added JavaScript DOM article by javascripttutorial.net in README.md file

Added JavaScript DOM article by javascripttutorial.net

---

README.md

**Purpose:**
In this pull request, I have added a video for Expression vs Statement.

Contribute: Added a video for Expression vs Statement

---

README.md

Created videos section and added javascript algorithms playlist - https://www.youtube.com/playlist?list=PLC3y8-rFHvwiRYB4-HHKHblh3_bQNJTMa

Added videos in under Algorithms

---

README.md

MDN reference for each of IIFE, Modules and Namespaces was added.

Added MDN references to 8. IIFE, Modules and Namespaces

---

README.md

Patterns.dev has concise explanations for every design pattern in JS with live sandboxes.

Added reference to Patterns.dev

---

README.md

I have modified the Twitter link to be a badge containing icon X which is clearer because the first look i haven't recognize that this is a twitter link :D. It more cool now <3

Add new Twitter Badge

---

README.md

Updated Readme.md and added video links on writting clean code in JS for issue #412

New clean code video tutorial added

---

README.md

1. Added license section to the read me 
2. Remove  the icons duplicated because this is a violation to the ui rules and instead add a gif to the beginning of the section indicating that this is either a reading source or video instead of using the same icon beside each list

Read me UI

---

README.md

@leonardomso can you check this?

Added a better new video link for DSA concepts

---

README.md

I've made some updates to this repository to enhance the content and categorization. Here's a summary of the changes:
1. JavaScript Engine: I've added a video link by Brad Traversy, which provides valuable insights into how JavaScript engines work. 
> Video Link: [Brad Traversy - Understanding JavaScript Engines](https://www.youtube.com/watch?v=oc6faXVc54E)
2. Collection and Generators: I've added a video link to this topic, which helps learners understand Collection and Generators 
> Video Link: [Collection and Generators](https://www.youtube.com/watch?v=dcP039DYzmE).
3. Clean Code: I've also added a video link that focuses on the importance of writing clean code.
> Video Link: [Tips to write clean code - Traversy Media](https://www.youtube.com/watch?v=0wHyoBPc6zs) 
In addition, I've …

Add Video Link to "JavaScript Engine", "Clean Code" and "Collection and Generators" Topics

---

README.md

Here's one more resource for learning JavaScript algorithms and data structures:
Daniel Shiffman, known for his contributions to creative coding and coding challenges, covers algorithms and data structures in a unique and engaging way. His explanations are interactive and suitable for both beginners and experienced developers.

Added a new best video for JavaScript algo and data structure

---

README.md

I have added Promise async and await in Javascript by Hitesh Choudhary in the readme file.

Added Async/Await Lecture

---

README.md

Added the concept of promise chaining.

added promise chaining

---

README.md

Adding hebrew translation

---

README.md

Added a video link under the heading 'JavaScript Engines'  which explains JS VM Internals, how event loop, callback works

Added a video link

---

README.md

"Added a new video link covering Modern Scope Handling in JavaScript (ES6 and Beyond) under '6. Function Scope, Block Scope, and Lexical Scope' as part of enhancing resources for the learning section. The video provides a clear explanation of scope concepts in modern JavaScript. This change addresses issue #508."
You can also mention that this is a non-technical contribution and that you're submitting it for Hacktoberfest, even if the issue wasn't assigned to you.

Added video link for Modern Scope Handling in JavaScript

---

README.md

changed the urdu translation repo URL because the author has changed his username.

changing Urdu Translation repo URL

---

README.md

"Add *yoruba* Yorùbá. "

---

README.md

Added Tamil translation of README and documentation. 
Link to my forked repo: https://github.com/UdayaKrishnanM/33-js-concepts

Updated Tamil language to the README.md
